name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: RUST_BACKTRACE=1 cargo build --verbose --all
    - name: Run tests with async-std
      run: RUST_BACKTRACE=1 cargo test --verbose --all --features=async-std,unstable
    - name: Run tests with tokio
      run: RUST_BACKTRACE=1 cargo test --verbose --all --features=tokio,unstable
